### ISSUE TITLE
Språk varning

### ISSUE THREAD

**Issue by jensadev** [Aragorn173/wu1-redesign#1]
https://github.com/Aragorn173/wu1-redesign/blob/6012526e51f5ae7a959abce1bdb8ad4009dc48d8/docs/index.html#L2

Har du validerat sidan? https://validator.nu/?doc=https%3A%2F%2Faragorn173.github.io%2Fwu1-redesign%2F

Skriv om det kort i PM

**Comment by Aragorn173** [comment]
Nu har jag validerat sidan och fixat alla errors och varningar som uppstått.
