### ISSUE TITLE
Fundera

### ISSUE THREAD

**Issue by jensadev** [Aragorn173/wu1-redesign#2]
https://github.com/Aragorn173/wu1-redesign/blob/6012526e51f5ae7a959abce1bdb8ad4009dc48d8/docs/index.html#L13

Kommer first_page, second_page skilja sig eller kan klasserna flyttas till body elementet?

**Comment by Aragorn173** [comment]
Jag kunde slå samman first_page och second_page eftersom dom var exakt likadana men när jag försökte flytta den till body elementet så ändrades storleken på headern.

**Comment by jensadev** [comment]
Kan ha ock göra med andra stilar för bredden eller höjden som påverkar den då den hamnar i ett annat element.
Det kan vara så att headern ska ligga utanför din main container rom du vill ha den en annan bredd.
